import Navbar from "@/section/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/section/Footer";

const poppins = Poppins({
    subsets: ["latin"],
    weight: [
        "300",
        "400",
        "500",
        "600",
        "700",
        "800",
    ],
});

export const metadata = {
    title: "Media Pergerakan",
    description:
        "Generated by create next app",
};

export default function RootLayout({
    children,
}) {
    return (
        <html lang="en">
            <body
                className={
                    poppins.className
                }
            >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
